# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - space-todo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build src/webapp/webapp.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/webapp/webapp.csproj -c Release -o "${{ github.workspace }}/artifacts/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/artifacts/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC3FEC5F61884E499A0E04E8E6B0A262 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E4D4B3B3ADD44028CECB8B37F6F406E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D8E7CB0FB9E74FBE8722FA52BF9BB54C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'space-todo'
          slot-name: 'Production'
          package: .
          